version: '3.5'

services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - './docker/nginx:/etc/nginx/conf.d'
            - './:/var/www/html'
        ports:
            - '80:80'